[theme]
primaryColor = "#e32033"  # Deep Blue
backgroundColor = "#f7fdff"  # Warm Gray
secondaryBackgroundColor = "#f0f2f6"  # Soft Blue
textColor = "#333333"  # Charcoal

[server]
headless = true
port = 8501 
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"


